### ISSUE TITLE
emo一下

### ISSUE THREAD

**Issue by yinziyan1206** [dtm-labs/rockscache#1]
延时锁的方式还是有很多人能想出来的，这个也用得上专利嘛。。。我很早前还在b站某缓存一致性介绍视频下评论过类似的办法呢。只是现在很多技术人员不愿意思考罢了，都是八股文害的。

**Comment by yedf2** [comment]
独创的地方不在于延时锁，您可以仔细看看原理。如果您有好的想法，可以提出来，或者给出链接，我可以一一解答

**Comment by yinziyan1206** [comment]
这我一进去看的读取数就是这原理嘛，后面还没细看。

**Comment by yedf2** [comment]
还没细看就开始踢馆子了...
