### ISSUE TITLE
rockscache能否支持go-redis v9版本

### ISSUE THREAD

**Issue by Wanghongw** [dtm-labs/rockscache#10]
rockscache的go.mod中还引用v8版本的go-redis，但是我们项目已经使用v9的go-redis了，初始化rockscache的client会报错:
cannot use rdb (variable of type *"github.com/redis/go-redis/v9".Client) as "github.com/go-redis/redis/v8".UniversalClient value in argument to rockscache.NewClient: *"github.com/redis/go-redis/v9".Client does not implement "github.com/go-redis/redis/v8".UniversalClient (wrong type for method AddHook)
            have AddHook("github.com/redis/go-redis/v9".Hook)
            want AddHook("github.com/go-redis/redis/v8".Hook)

是否可以支持下v9版本的go-redis？

**Comment by Wanghongw** [comment]
大概看了下，go-redis v9版本的Client没有实现 Context()方法，这个什么时候可以支持下go-redis v9版本？

**Comment by exuan** [comment]
https://github.com/dtm-labs/rockscache/pull/13
