### ISSUE TITLE
可以添加一个是否缓存的条件么？

### ISSUE THREAD

**Issue by dahvlhldle** [dtm-labs/rockscache#19]
我想根据查询结果来判断是否缓存，请问可以添加一个是否缓存的条件么？
v, err := rc.Fetch("key1", 300 * time.Second, func()(string, bool,error) {
  // fetch data from database or other sources
 notneedcache=false
 return "value1",notneedcache, nil
})

**Comment by yedf2** [comment]
这种的场景比较少，不建议这么处理

**Comment by dahvlhldle** [comment]
OK
