### ISSUE TITLE
文中的demo会报错

### ISSUE THREAD

**Issue by kacha886** [dtm-labs/rockscache#2]
func main() {
	client := redis.NewClient(&redis.Options{
		Network: "tcp",
		Addr:    "127.0.0.1:6379",
		DB:      0,
	})

	rc := rockscache.NewClient(client, rockscache.NewDefaultOptions())
	v, err := rc.Fetch("key2", 400, func() (string, error) {
		return "value2", nil
	})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(v)
}
key2的值为"aaa"，获取时报下面的错误
ERR Error running script (call to f_a307994a908d94d53a2b772ddc6cf08109e0a828): @user_script:2: WRONGTYPE Operation against a key holding the wrong kind of value

**Comment by yedf2** [comment]
key2的值，或者为空，或者为hash，而不是string。你可以删掉key2，重新运行一下
