### ISSUE TITLE
About the lockuntil is expired, and the data is also expired when data is not empty?

### ISSUE THREAD

**Issue by nebulaoc** [dtm-labs/rockscache#23]
Why think that when the data is not empty, the lock expires and the data also expires?Why not use the TagAsDeleted function as the only trigger for cache updates？

I saw the code about default lockexpire time is 3s.Does it mean that an asynchronous update will be triggered every 3s, regardless of whether the data in the database is updated or not?

**Comment by yedf2** [comment]
> Why not use the TagAsDeleted function as the only trigger for cache updates？

If some unexpected errors happened, nothing can be ensured. So we assume when the lock expires, we can overwrite the data.

**Comment by nebulaoc** [comment]
Thanks.
