### ISSUE TITLE
Which scene do you need to use mark deletion?

### ISSUE THREAD

**Issue by jiayiming001** [dtm-labs/rockscache#6]
Which scene do you need to use mark deletion?
![image](https://user-images.githubusercontent.com/32919372/186368912-56d0e301-f164-4a6b-a661-117ec2b8fd5d.png)

**Comment by yedf2** [comment]
If you delete the data in redis directly, then it is unable to avoid the problem of old versions overwriting new ones

**Comment by jiayiming001** [comment]
i think so long,  use “del”  command  direct  delete ,   is useful

**Comment by jiayiming001** [comment]
but during 10s   data of taged  in redis  is drty. so the clinet maybe read this dirty data.

**Comment by yedf2** [comment]
You can read the document, all is explained.

If you delete it directly, there are also dirty data. If dirty data is not acceptable, you can enable strong consistency

**Comment by jiayiming001** [comment]
thanks
